routes/book.py
from flask import Blueprint, request, jsonify,render_template,redirect,url_for,session,flash
from mysql.connector import Error
from config.database import getDatabase
import smtplib,os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta

book_bp = Blueprint("books", __name__)

#kitap listeleme
@book_bp.route("/books", methods=["GET"])
def list_books():
        
    connection = getDatabase()
    if connection is None:
        error_msg = "Veri tabanı bağlantısı kurulamadı."
        if request.headers.get('Accept') == 'application/json':
            return jsonify({"error": error_msg}), 500
        return render_template("index.html", error=error_msg)
    
    cursor = connection.cursor(dictionary=True)
    
    try:
        cursor.execute("SELECT * FROM book")
        books = cursor.fetchall()
        
        if not books:
            message = "Kayıtlı kitap bulunamadı"
            if request.headers.get('Accept') == 'application/json':
                return jsonify({"message": message, "books": []}), 200
            return render_template("books.html", books=[], message=message)
        
        if request.headers.get('Accept') == 'application/json' or request.args.get('format') == 'json':
            return jsonify({"books": books}), 200
        
        return render_template("books.html", books=books)
    
    except Error as e:
        print(f"Hata oluştu: {e}")
        error_msg = "Kitaplar listelenirken bir hata oluştu."
        if request.headers.get('Accept') == 'application/json':
            return jsonify({"error": error_msg}), 500
        return render_template("books.html", error=error_msg)
    
    finally:
        cursor.close()
        connection.close()


#Kitap ekleme
@book_bp.route("/addBook", methods=['GET','POST'])
def addBook():
    
    if "user_id" not in session:
        if request.is_json:
            return jsonify({"error": "Bu sayfaya erişmek için giriş yapmalısınız."}), 401
        flash("Bu sayfaya erişmek için giriş yapmalısınız.", "warning")
        return redirect(url_for("auth.login"))

    if session.get('role') != 'admin':
        flash('Bu sayfaya erişim yetkiniz yok!', 'danger')
        print("bu sayfaya sadece adminler giriş yapabilir")
        return redirect(url_for('index'))
        
    if request.method == "POST":
        if request.is_json:
            data = request.get_json()
            title = data.get("title")
            author_name = data.get("author_name")
            category_name = data.get("category_name")
            isbn = data.get("isbn")
            publish_year = data.get("publish_year")
            description = data.get("description")
            if not description:
                description = "açıklama yok"
        
        else:
            title = request.form["title"]
            author_name = request.form["author_name"]
            category_name = request.form["category_name"]
            isbn = request.form["isbn"]
            publish_year = request.form["publish_year"]
            description = request.form.get("description", "").strip() or "açıklama yok"
        
        
        if not all([title, author_name, category_name, isbn, publish_year]):
            message = "Lütfen tüm zorunlu alanları doldurun."
            if request.is_json:
                return jsonify({"error": message}), 400
            else:
                return render_template("addBook.html", 
                                 message=message,
                                 form_data=request.form)
    
        connection = getDatabase()
        if connection is None:
            error_msg = "Veri tabanı bağlantısı kurulamadı."
            if request.is_json:
                return jsonify({"error": error_msg}), 500
            return render_template("addBook.html", error=error_msg)
        
        cursor = connection.cursor(dictionary=True)
        try:
            cursor.execute("SELECT * FROM book WHERE isbn = %s", (isbn,))
            isbn_control = cursor.fetchone()
            
            if isbn_control:
                message = "Bu ISBN numarası başka bir kitaba aittir."
                if request.is_json:
                    return jsonify({"error": message}), 409
                else:
                    return render_template("addBook.html", message=message)
            
            cursor.execute("INSERT INTO book (title, author_name, category_name, isbn, publish_year, description) VALUES (%s, %s, %s, %s, %s, %s)",
                      (title, author_name, category_name, isbn, publish_year, description))
            connection.commit()
            
            cursor.execute("SELECT * FROM book WHERE isbn = %s", (isbn,))
            inserted_book = cursor.fetchone()
            
            if request.is_json:
                return jsonify({
                    "message": "Kitap başarıyla eklendi!",
                    "book": inserted_book
                }), 201
            else:
                flash(f"'{title}' başlıklı kitap başarıyla eklendi.", "success")
                return redirect(url_for("books.list_books"))
                
        except Error as e:
            connection.rollback()
            print(f"Hata oluştu: {e}")
            error_msg = "Kitap eklenirken bir hata oluştu."
            if request.is_json:
                return jsonify({"error": error_msg}), 500
            return render_template("addBook.html", error=error_msg)
        finally:
            cursor.close()
            connection.close()
            
    return render_template("addBook.html")


#kitap silme
@book_bp.route("/deleteBook", methods=['GET', 'POST'])
def deleteBook():

    if "user_id" not in session:
        if request.is_json:
            return jsonify({"error": "Bu sayfaya erişmek için giriş yapmalısınız."}), 401
        flash("Bu sayfaya erişmek için giriş yapmalısınız.", "warning")
        return redirect(url_for("auth.login"))
    
    if session.get('role') != 'admin':
        flash('Bu sayfaya erişim yetkiniz yok!', 'danger')
        print("bu sayfaya sadece adminler giriş yapabilir")
        return redirect(url_for('index'))
    
        
    if request.method == "POST":
        if request.is_json:
            data = request.get_json()
            isbn = data.get("isbn")
        else:
            isbn = request.form.get("isbn")

        if not isbn:
            message = "Kaydı silinecek kitabın ISBN numarası girilmelidir!"
            if request.is_json:
                return jsonify({"error": message}), 400
            return render_template("deleteBook.html", Warning=message)
            
        if not isbn.isdigit():
            message = "Silinecek kitabın ISBN numarası rakamlardan oluşmalı."
            if request.is_json:
                return jsonify({"error": message}), 400
            return render_template("deleteBook.html", error=message) 

        connection = getDatabase()
        if connection is None:
            error_msg = "Veri tabanı bağlantısı kurulamadı."
            if request.is_json:
                return jsonify({"error": error_msg}), 500
            return render_template("deleteBook.html", error=error_msg)
        
        cursor = connection.cursor(dictionary=True)
        
        try:
            cursor.execute("SELECT * FROM book WHERE isbn = %s", (isbn,))
            book = cursor.fetchone()
            
            if not book:
                cursor.close()
                connection.close()
                message = "Bu ISBN numarasına sahip kitap bulunamadı!"
                if request.is_json:
                    return jsonify({"error": message}), 404
                return render_template("deleteBook.html", message=message)

            cursor.execute("DELETE FROM book WHERE isbn = %s", (isbn,))
            
            if cursor.rowcount > 0:
                connection.commit()
                if request.is_json:
                    return jsonify({
                        "message": "Kitap başarıyla silindi!",
                        "deleted_book": book
                    }), 200
                else:
                    flash(f"'{book['title']}' başlıklı kitap başarıyla silindi.", "success")
                    return redirect(url_for("books.list_books"))
            else:
                message = "Silme işlemi başarısız oldu!"
                if request.is_json:
                    return jsonify({"error": message}), 500
                return render_template("deleteBook.html", message=message)

        except Error as e:
            connection.rollback()
            print(f"Hata oluştu: {e}")
            error_msg = "Kitap silinirken hata oluştu."
            if request.is_json:
                return jsonify({"error": error_msg}), 500
            return render_template("deleteBook.html", error=error_msg)

        finally:
            cursor.close()
            connection.close()

    return render_template("deleteBook.html")


#Kitap bilgilerini gösterme(bir kitap)
@book_bp.route("/bookInfo/<int:id>")
def bookInfo(id):
         
    connection = getDatabase()
    if connection is None:
        error_msg = "Veri tabanı bağlantısı kurulamadı."
        if request.is_json or request.args.get('format') == 'json':
            return jsonify({"error": error_msg}), 500
        return render_template("bookInfo.html", error=error_msg)
    
    cursor = connection.cursor(dictionary=True)
    try:
        cursor.execute("SELECT * FROM book WHERE book_id = %s", (id,))
        book = cursor.fetchone()
          
        if book:
            if request.is_json or request.args.get('format') == 'json':
                return jsonify({
                    "message": "Kitap bulundu",
                    "book": book
                }), 200
            return render_template("bookInfo.html", books=book)
        else:
            message = f"ID {id} numaralı kitap bulunamadı."

templates/addBook.html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <title>Kitap Ekle</title>
    <link rel="stylesheet" href="static\css\addBook.css">
</head>
<body>
    <h2 class="yazi1">Kitap Ekle</h2>

    <div class="form-container">
        {% if message %}
            <p class="message">{{ message }}</p>
        {% endif %}

        <form action="{{ url_for('books.addBook') }}" method="POST">

            <div class="form-group">
                <label>Kitap Adı:</label>
                <input type="text" name="title" required placeholder="Kitap adını giriniz.">
            </div>
            
            <div class="form-group">
                <label>Yazar Adı:</label>
                <input type="text" name="author_name" required placeholder="Yazar Adını giriniz.">
            </div>

            <div class="form-group">
                <label>Kategorisi:</label>
                <input type="text" name="category_name" required placeholder="Kitabın kategorisini giriniz.">
            </div>

            <div class="form-group">
                <label>ISBN numarası:</label>
                <input type="text" name="isbn" required placeholder="Kitabın isbn numarasını giriniz.">
            </div>

            <div class="form-group">
                <label>Yayınlandığı Yıl:</label>
                <input type="text" name="publish_year" required placeholder="Kitabın yayınlandığı yılı giriniz.">
            </div>

            <div class="form-group">
                <label>Kitap Açıklama:</label>
                <input type="text" name="description" placeholder="Kitap açıklaması.">
            </div>
            <button type="submit" class="submit-btn">EKLE</button>

            <!-- ana sayfaya dön butonu eklenecek-->

        </form>
    </div>
</body>
</html>

templates/adminIndex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Ana Sayfası</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="static/css/adminIndex.css">
</head>

<body>
    <div class="container">
        <header>
            <h1 class="yazi1">
                <span class="register">
                    <a href="{{ url_for('auth.register') }}"><i class="fa-solid fa-user-plus"></i> Kayıt Ol</a>
                </span>
                Kütüphane Yönetim Sistemi
                <span class="logout">
                    <a href="{{ url_for('auth.logout') }}"><i class="fa-solid fa-right-from-bracket"></i> Çıkış Yap</a>
                </span>
            </h1>
        </header>

        <main class="ortabar">
            <div class="menu-grid">
                <div class="menu-item ekle">
                    <div class="menu-content">
                        <div class="menu-icon">
                            <i class="fa-solid fa-book"></i>
                        </div>
                        <div class="menu-text">
                            <h3>Kitap Ekle</h3>
                            <p>Yeni kitap ekleyin</p>
                        </div>
                    </div>
                    <a class="menu-link" href="{{url_for('books.addBook')}}"></a>
                </div>

                <div class="menu-item sil">
                    <div class="menu-content">
                        <div class="menu-icon">
                            <i class="fa-solid fa-trash"></i>
                        </div>
                        <div class="menu-text">
                            <h3>Kitap Sil</h3>
                            <p>Kayıttan kitap silin</p>
                        </div>
                    </div>
                    <a class="menu-link" href="{{url_for('books.deleteBook')}}"></a>
                </div>

                <div class="menu-item listele">
                    <div class="menu-content">
                        <div class="menu-icon">
                            <i class="fa-solid fa-list-ul"></i>
                        </div>
                        <div class="menu-text">
                            <h3>Kitap Listesi</h3>
                            <p>Tüm kitapları görüntüleyin</p>
                        </div>
                    </div>
                    <a class="menu-link" href="{{url_for('books.list_books')}}"></a>
                </div>

                <div class="menu-item ara">
                    <div class="menu-content">
                        <div class="menu-icon">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </div>
                        <div class="menu-text">
                            <h3>Kitap Ara</h3>
                            <p>Kitap araması yapın</p>
                        </div>
                    </div>
                    <a class="menu-link" href="{{url_for('books.bookSearch')}}"></a>
                </div>

            </div>
        </main>

        <div class="image-container">
            <div class="ortabar2">
                <img src="/static/images/library_images1.png" alt="resim eklenemedi.">
            </div>

            <div class="ortabar3">
                <img src="/static/images/library_images2.png" alt="resim eklenemedi.">
            </div>
        </div>

        <footer class="footer">
            <div class="footer-content">
                <div class="footer-info">
                    <h3>Geliştirici Bilgileri</h3>
                    <div class="contact-links">
                        <a href="https://github.com/firatoz412" target="_blank" title="GitHub">
                            <i class="fa-brands fa-github"></i>
                            <span>Github</span>
                        </a>
                        <a href="mailto:firatoz412@gmail.com" title="E-posta">
                            <i class="fa-solid fa-envelope"></i>
                            <span>E-mail</span>
                        </a>
                        <a href="#" target="_blank" title="LinkedIn">
                            <i class="fa-brands fa-linkedin"></i>
                            <span>LinkedIn</span>
                        </a>
                    </div>
                </div>
                <div class="footer-bottom">
                    <p>&copy; 2025 Kütüphane Yönetim Sistemi.</p>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

templates/adminLogin.html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Giriş Sayfası</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="static\css\login.css">
</head>
<body>
    <div class="container">
        <h1>Giriş Yap</h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div style="color:red" class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <form method="POST">
            <div class="form-group">
                <label for="username">Kullanıcı Adı:</label>
                <input type="text" id="username" name="username" required autofocus>
            </div>
 
            <div class="form-group">
                <label for="password">Şifre:</label>
                <input type="password" id="password" name="password" required>
            </div>

            <button type="submit">Giriş Yap</button>
        </form>

        <div class="links">
            <p>Hesabınız yok mu? <a href="{{ url_for('auth.register') }}">Kayıt Ol</a></p>
        </div>

        <div class="back-home">
            <a href="{{ url_for('index') }}">Ana Sayfaya Dön</a>
        </div>

        

    </div>
</body>
</html>

templates/adminPanel.html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Paneli</title>
    <link rel="stylesheet" href="static\css\adminPanel.css">
</head>
<body>
    <div class="container">
        <h1>Admin Paneli</h1>
        <p class="welcome">Hoş geldiniz {{ session.name }} {{session.surename}}</p>
        
        <div class="nav-links">
            <a href="{{ url_for('admin.adminIndex') }}">Ana Sayfa</a>
            <a href="{{ url_for('books.list_books') }}">Kitaplar</a>
            <a href="{{ url_for('auth.logout') }}"> Çıkış</a>
        </div>

        <div class="admin-menu">
            <a href="{{ url_for('books.addBook') }}" class="menu-card">
                <h3>Kitap Ekle</h3>
                <p>Kütüphaneye yeni kitap ekleyin</p>
            </a>
            
            <a href="{{ url_for('books.deleteBook') }}" class="menu-card">
                <h3>Kitap Sil</h3>
                <p>Mevcut kitapları silin</p>
            </a>
            
            
            <a href="{{ url_for('books.bookSearch') }}" class="menu-card">
                <h3>Kitap Ara</h3>
                <p>Kitap bilgilerini sorgulayın</p>
            </a>
            
            <a href="{{ url_for('books.list_books') }}" class="menu-card">
                <h3>Tüm Kitaplar</h3>
                <p>Kitap listesini görüntüleyin</p>
            </a>

            <a href="{{ url_for('admin.userList') }}" class="menu-card">
                <h3>Kayıtlı Kullanıcılar</h3>
                <p>Kayıtlı kullanıcıları görüntüleyinç.</p>
            </a>

            <a href="{{ url_for('admin.list_penalties') }}" class="menu-card">
                <h3>Cezalı Kullanıcılar </h3>
                <p>Ceza Almış Kullanıcıları Görüntüleyin.</p>
            </a>
        </div>
    </div>
</body>
</html>

templates/adminRegister.html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Kayıt Sayfası</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="static\css\register.css">
</head>
<body>
    <div class="container">
        <h1>Kayıt Ol</h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <form method="POST">
            <div class="form">
                <label for="username">Ad:</label>
                <input type="text" id="name" name="name" required autofocus>
            </div>

            <div class="form">
                <label for="username">Soyad:</label>
                <input type="text" id="surename" name="surename" required autofocus>
            </div>

            <div class="form">
                <label for="username">Kullanıcı Adı:</label>
                <input type="text" id="username" name="username" required autofocus>
            </div>

            <div class="form">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>

            <div class="form">
                <label for="password">Şifre:</label>
                <input type="password" id="password" name="password" required>
            </div>

            <div class="form">
                <label for="passwordConfirm">Şifre Tekrar:</label>
                <input type="password" id="passwordConfirm" name="passwordConfirm" required>
            </div>

            <button type="submit">Kayıt Ol</button>
        </form>

        <div class="links">
            <p>Zaten hesabınız var mı? <a href="{{ url_for('auth.login') }}">Giriş Yap</a></p>
        </div>

        <div class="back-home">
            <a href="{{ url_for('index') }}">Ana Sayfaya Dön</a>
        </div>
        
    

    </div>
</body>
</html>

templates/bookInfo.html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kitap Detayları</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=undo" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bookInfo.css') }}">
</head>
<body>
    <div class="container">
        <h1 class="yazi">Kitap Detayları</h1>
        
        {% if books %}
            <div class="info">
                <p><i>Kitap Adı:{{books.title}}</i></p>
                <p><i>Kitap Yazarı: {{books.author_name}}</i></p>
                <p><i> Kategorisi:{{books.category_name}}</i></p>
                <p><i>ISBN Numarası: {{books.isbn}}</i></p>
                <p><i>Kitabın Yayın Yılı: {{books.publish_year}}</i></p>
                <p><i>Kitabın Konusu:{{books.description}}</i></p>
            </div>
        {% else %}
            <div class="alert">
                Kitap bulunamadı!
            </div>
        {% endif %}

        <div class="link-container">
            <div class="link">
                <a href="{{ url_for('books.list_books') }}">
                    <span class="material-symbols-outlined">undo</span>
                    Kitap Listesi
                </a>
            </div>

            <div class="link">
                <a href="{{ url_for('books.bookSearch') }}">
                    <span class="material-symbols-outlined">undo</span>
                    Kitap Arama
                </a>
            </div>

            <div class="link">
                <a href="{{ url_for('index') }}">
                    <span class="material-symbols-outlined">undo</span>
                    Ana Sayfaya Dön
                </a>
            </div>
        </div>
    </div>
</body>
</html>

templates/bookSearch.html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kitap Ara</title>
    <link rel="stylesheet" href="static\css\bookSearch.css">
</head>
<body>
    <div class="search-container">
        <h2>Kitap Ara 🔍</h2>
        <p class="subtitle">Aramak İstediğiniz Kitap ID'sini girin</p>
        
        <form action="{{ url_for('books.bookSearch') }}" method="POST" class="search-form">
            <div class="form-group">
                <label for="isbn" style="padding-left:15px">Kitap İSBN numarası:</label>
                <div class="input-container">
                    <input type="text" name="isbn" required 
                           placeholder="Örn: 13 haneli isbn numarası" 
                           autocomplete="off"
                           title="Sadece rakam giriniz">
                </div>
            </div>
            
            <button type="submit" class="search-btn">
                <span class="btn-icon">🔍</span>
                ARA
            </button>
        </form>
    </div>
</body>
</html>

templates/books.html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kitaplar</title>
    <link rel="stylesheet" href="static\css\books.css">
</head>
<body>

<div class="container">

    <header>
        <h2>Kitap Listesi</h2>
    </header>

    <div class="table-wrapper">
        <table>
            <thead>
                <tr>
                    <th class="baslik">ID</th>
                    <th class="baslik">Kitap Adı</th>
                    <th class="baslik">Yazar</th>
                    <th class="baslik">Kategori</th>
                    <th class="baslik">ISBN</th>
                    <th class="baslik">Basım Yılı</th>
                    <th class="baslik">Açıklama</th>
                    <th class="baslik">İşlemler</th>
                </tr>
            </thead>

            <tbody>
                {% for book in books %}
                <tr>
                    <td>{{ book["book_id"] }}</td>
                    <td>{{ book["title"] }}</td>
                    <td>{{ book["author_name"] }}</td>
                    <td>{{ book["category_name"] }}</td>
                    <td>{{ book["isbn"] }}</td>
                    <td>{{ book["publish_year"] }}</td>
                    <td>{{ book["description"] if book["description"] else "Açıklama Yok" }}</td>
                    <td>
                        <div class="action-buttons-row">
                            <a href="{{ url_for('books.borrowBook', book_id=book['book_id']) }}" class="action-btn borrow-btn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9zM1 7v1h14V7zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5m2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5"/>
                                </svg>
                                <span>Ödünç Al</span>
                            </a>
                            <a href="{{ url_for('books.returnBook', book_id=book['book_id']) }}" class="action-btn return-btn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 3a5 5 0 1 1-4.546 2.914.5.5 0 0 0-.908-.417A6 6 0 1 0 8 2z"/>
                                    <path d="M8 4.466V.534a.25.25 0 0 0-.41-.192L5.23 2.308a.25.25 0 0 0 0 .384l2.36 1.966A.25.25 0 0 0 8 4.466"/>
                                </svg>
                                <span>İade Et</span>
                            </a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>

    
</div>

</body>
</html>

templates/deleteBook.html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kitap Sil</title>
    <link rel="stylesheet" href="static\css\deleteBook.css">
</head>
<body>
    <div class="main-container">
        <h2 class="yazi1">Kitap Silme</h2>

        <form action="{{ url_for('books.deleteBook') }}" method="POST">
            <div class="form-group">
                <label class="label1">Silinecek Kitabsın ISBN numarsı:</label>
                <input type="text" name="isbn" required placeholder="Örn: 1234567891011(13 haneli)" autocomplete="off">
            </div>
     
            <div class="button-container">
                <button type="submit" class="delete-btn">Sil</button>
                <a href="{{ url_for('books.list_books') }}" class="list-link">Kitap Listesi</a>
            </div>  
        </form>
    </div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Giriş Yap</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="static\css\login.css">
</head>
<body>
    <div class="container">
        <h1>Giriş Yap</h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div style="color:red" class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <form method="POST">
            <div class="form-group">
                <label for="username">Kullanıcı Adı:</label>
                <input type="text" id="username" name="username" required autofocus>
            </div>
 
            <div class="form-group">
                <label for="password">Şifre:</label>
                <input type="password" id="password" name="password" required>
            </div>

            <button type="submit">Giriş Yap</button>
        </form>

        <div class="links">
            <p>Hesabınız yok mu? <a href="{{ url_for('auth.register') }}">Kayıt Ol</a></p>
        </div>

        <div class="back-home">
            <a href="{{ url_for('index') }}">Ana Sayfaya Dön</a>
        </div>

        <div class="admin-login">
            <a href="{{ url_for('admin.adminLogin', admin=1) }}" class="admin-btn">
                Admin Girişi
            </a>
        </div>
    </div>
</body>
</html>